#define NUM_OF_COLUMNS 8
#define MUX_PIN_A 4
#define MUX_PIN_B 5
#define MUX_PIN_C 6
#define MUX_INHIBIT_PIN 2
#define COLUMNS_PITCH_PIN A7
#define COLUMNS_TOGGLE_PIN 7

#define CONTROLS_SHAPE_PIN A4
#define CONTROLS_MODULATION_PIN A5
#define CONTROLS_TEMPO_PIN A6
#define CONTROLS_DURATION_PIN A3

#define DEBUG_PIN 13